name: C++ CI with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the code
    - name: Set up CMake
      run: sudo apt install libgtest-dev  # Install necessary dependencies for CMake and Google Test
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make  # Build the project
    - name: Run tests
      run: |
        cd build
        ./calculator_tests  # Adjust this based on your test executable
